### ISSUE TITLE
Q: ssl Connection on php-lib requires validation and client certs

### ISSUE THREAD

**Issue by basz** [prolic/HumusAmqp#9]
I noticed while testing the SslConnection class requires the verify to be true. Also it requires a client cert pair.

I'm wondering why? I can create a encrypted connection without both if I use the lib directly. Might be stupid question as I do not fully understand why client cert would be needed anyway.

**Comment by prolic** [comment]
I did not finish writing tests for the ssl part. Will come back to you, when I am done with it.

**Comment by prolic** [comment]
This is now fixed in current master.
see: https://github.com/prolic/HumusAmqp/blob/master/tests/AmqpExtension/ConnectionTest.php#L129
and: https://github.com/prolic/HumusAmqp/blob/master/tests/PhpAmqpLib/SslConnectionTest.php

**Comment by dl1ely** [comment]
Sorry for chiming in here again, but HumusAMQP still enforces client-side certificates (https://github.com/prolic/HumusAmqp/blob/master/src/Driver/PhpAmqpLib/SslConnection.php#L50), while php-amqplib does not need client-side-certificates. I think that is exactly what @basz was asking. Writing tests for that behaviour does not fix it IMHO. What is the rationale to throw an exception when no client-side certificate file is given in the options?

Thank you!

**Comment by prolic** [comment]
Thanks for pointing this out. I will take a deeper look again the next days.

**Comment by dl1ely** [comment]
OK, great, thank you. As far as i can see, removing the checks in https://github.com/prolic/HumusAmqp/blob/master/src/Driver/PhpAmqpLib/SslConnection.php#L50-L56 should suffice? php-amqplib should work fine without the values that are enforced there. Thanks for looking into that issue.

**Comment by prolic** [comment]
And you think ca cert is still required? Just asking so I got as much information as possible before I look into this.

**Comment by dl1ely** [comment]
Well, if you force verify=true, you need the cacert file, else verification cannot be done (As there is no CA trust chain). If verify is set to false, cacert can be omitted, too. But verifying the server identity with verify=true using the CA trust chain (Like the browser is doing when connecting a https web page) is a much more common usecase than being forced to supply a client certificate. So cacert must be set if verify is true, all other cases are optional.

**Comment by prolic** [comment]
@basz I could connect to RabbitMQ using letsencrypt certs, it was no problem at all. But for me to make it work, I had to set "verify" = false.

**Comment by basz** [comment]
Right, Well it does not work for me. Ive noticed subtle differences between versions of rabbitmq, the installed erlang version and operating systems. Thinking containerizing this I ran into an issue with the official docker releases where I needed to set env cars just for erlang to be able to connect over TLS. With some help of @bweston92 i was able to get that working.

(Does prooph would like to offer a dockerized rabbitmq container? Not that is finished, but...)

Well anyways - I'll try again and see what happens... but it think I should move everything to docker anyway eventually...


Anyway
